# Generated by Django 6.1 on 2026-09-02 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                related_name="registered_cars", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
